version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: "1.75"
  commands:
    - pip install maturin
    - maturin build
    - pip install target/wheels/peppi_py-0.7.0*.whl

sphinx:
  configuration: docs/conf.py
