version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: "1.75"
  commands:
    - python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
    - python -m pip install --upgrade --no-cache-dir pip setuptools sphinx readthedocs-sphinx-ext maturin
    - maturin build
    - python -m pip install --no-cache-dir target/wheels/peppi_py-*.whl
    - cd docs && python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
